name: Go Continuous Integration Workflow

on:
  push:
    branches:
      - master
      - staging
      - develop
      - feature/*
  pull_request:
    branches:
      - master
      - staging
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/clockbox:latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #   - name: Setup Go
    #     uses: actions/setup-go@v3
    #   - uses: actions/setup-go@v4
    #     with:
    #       go-version: "1.20"
    #       check-latest: true
    #       run: |
    #         go version
    #         go env
    #   #      - name: export gopath
    #   #        run: echo "GOPATH=$HOME/go" >> $GITHUB_ENV
    #   #      - name: export go bin
    #   #        run: echo "$GOPATH/bin" >> $GITHUB_PATH
    #   - name: read all path
    #     run: echo $PATH
    #   - name: Verify Dependency
    #     run: go mod verify
    #   - name: Install all Dependency
    #     run: |
    #       go mod tidy
    #       go get -u golang.org/x/lint/golint
    #   - name: Run Build
    #     run: go build .
    #   # Run vet & lint on the code
    #   - name: Run vet & lint
    #     run: |
    #       go vet .
    #       golint .
    #   # Run testing on the code
    #   - name: Run testing
    #     run: cd test && go test -v
